
CREATE TABLE Category (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE,
  code VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE User (
  id INT PRIMARY KEY AUTO_INCREMENT,
  reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  contacts VARCHAR(50) NOT NULL
);

CREATE TABLE Lot (
 id INT PRIMARY KEY AUTO_INCREMENT,
 creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 name VARCHAR(50) NOT NULL,
 description  VARCHAR(255) NOT NULL,
 image VARCHAR(255) NOT NULL,
 end_date DATE NOT NULL,
 start_price INT NOT NULL,
 bidding_step INT NOT NULL,

 author_id INT NOT NULL,
 winner_id INT,
 category_id INT NOT NULL,
 FOREIGN KEY (author_id) REFERENCES User(id) ON DELETE CASCADE,
 FOREIGN KEY (winner_id) REFERENCES User(id) ON DELETE CASCADE,
 FOREIGN KEY (category_id) REFERENCES Category(id) ON DELETE CASCADE
);

CREATE TABLE Bid (
 id INT PRIMARY KEY AUTO_INCREMENT,
 bid_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 sum INT NOT NULL,

 user_id INT NOT NULL,
 lot_id INT NOT NULL,
 FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
 FOREIGN KEY (lot_id) REFERENCES Lot(id) ON DELETE CASCADE
);

